apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-map-volume
spec:
  storageClassName: minecraft-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
