steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/perfect-chalice-250601/minecraft:latest
  - --destination=gcr.io/perfect-chalice-250601/minecraft:$REVISION_ID
  - --cache=true
  - --cache-ttl=730h
