apiVersion: v1
data:
  spigot.yml: |
    # This is the main configuration file for Spigot.
    # As you can see, there's tons to configure. Some options may impact gameplay, so use
    # with caution, and make sure you know what each option does before configuring.
    # For a reference for any variable inside this file, check out the Spigot wiki at
    # http://www.spigotmc.org/wiki/spigot-configuration/
    #
    # If you need help with the configuration or have any questions related to Spigot,
    # join us at the IRC or drop by our forums and leave a post.
    #
    # IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
    # Forums: http://www.spigotmc.org/

    config-version: 12
    settings:
      debug: true
      save-user-cache-on-stop-only: false
      late-bind: false
      bungeecord: false
      sample-count: 12
      player-shuffle: 0
      user-cache-size: 1000
      moved-wrongly-threshold: 0.0625
      moved-too-quickly-multiplier: 10.0
      timeout-time: 60
      restart-on-crash: true
      restart-script: ./run.sh
      netty-threads: 4
      attribute:
        maxHealth:
          max: 2048.0
        movementSpeed:
          max: 2048.0
        attackDamage:
          max: 2048.0
    messages:
      whitelist: You are not whitelisted on this server! Msg Kirin to be added
      unknown-command: Unknown command. Type "/help" for help.
      server-full: The server is full!
      outdated-client: Outdated client! Please use {0}
      outdated-server: Outdated server! I'm still on {0}
      restart: Server is restarting
    commands:
      spam-exclusions:
      - /skill
      silent-commandblock-console: false
      replace-commands:
      - setblock
      - summon
      - testforblock
      - tellraw
      log: true
      tab-complete: 0
      send-namespaced: true
    advancements:
      disable-saving: false
      disabled:
      - minecraft:story/disabled
    stats:
      disable-saving: false
      forced-stats: {}
    world-settings:
      default:
        view-distance: default
        verbose: true
        mob-spawn-range: 6
        hopper-amount: 1
        dragon-death-sound-radius: 0
        seed-village: 10387312
        seed-desert: 14357617
        seed-igloo: 14357618
        seed-jungle: 14357619
        seed-swamp: 14357620
        seed-monument: 10387313
        seed-shipwreck: 165745295
        seed-ocean: 14357621
        seed-outpost: 165745296
        seed-slime: 987234911
        max-tnt-per-tick: 100
        enable-zombie-pigmen-portal-spawns: true
        item-despawn-rate: 6000
        arrow-despawn-rate: 1200
        wither-spawn-sound-radius: 0
        hanging-tick-frequency: 100
        zombie-aggressive-towards-villager: true
        nerf-spawner-mobs: false
        merge-radius:
          exp: 3.0
          item: 2.5
        growth:
          bamboo-modifier: 100
          sweetberry-modifier: 100
          kelp-modifier: 100
          cactus-modifier: 100
          cane-modifier: 100
          melon-modifier: 100
          mushroom-modifier: 100
          pumpkin-modifier: 100
          sapling-modifier: 100
          beetroot-modifier: 100
          carrot-modifier: 100
          potato-modifier: 100
          wheat-modifier: 100
          netherwart-modifier: 100
          vine-modifier: 100
          cocoa-modifier: 100
        entity-activation-range:
          raiders: 48
          animals: 32
          monsters: 32
          misc: 16
          tick-inactive-villagers: true
        entity-tracking-range:
          players: 48
          animals: 48
          monsters: 48
          misc: 32
          other: 64
        ticks-per:
          hopper-transfer: 8
          hopper-check: 1
        hunger:
          jump-walk-exhaustion: 0.05
          jump-sprint-exhaustion: 0.2
          combat-exhaustion: 0.1
          regen-exhaustion: 6.0
          swim-multiplier: 0.01
          sprint-multiplier: 0.1
          other-multiplier: 0.0
        max-tick-time:
          tile: 50
          entity: 50
        squid-spawn-range:
          min: 45.0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"spigot","creationTimestamp":null},"data":{"spigot.yml":"# This is the main configuration file for Spigot.\n# As you can see, there's tons to configure. Some options may impact gameplay, so use\n# with caution, and make sure you know what each option does before configuring.\n# For a reference for any variable inside this file, check out the Spigot wiki at\n# http://www.spigotmc.org/wiki/spigot-configuration/\n#\n# If you need help with the configuration or have any questions related to Spigot,\n# join us at the IRC or drop by our forums and leave a post.\n#\n# IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )\n# Forums: http://www.spigotmc.org/\n\nconfig-version: 12\nsettings:\n  debug: true\n  save-user-cache-on-stop-only: false\n  late-bind: false\n  bungeecord: false\n  sample-count: 12\n  player-shuffle: 0\n  user-cache-size: 1000\n  moved-wrongly-threshold: 0.0625\n  moved-too-quickly-multiplier: 10.0\n  timeout-time: 60\n  restart-on-crash: true\n  restart-script: ./run.sh\n  netty-threads: 4\n  attribute:\n    maxHealth:\n      max: 2048.0\n    movementSpeed:\n      max: 2048.0\n    attackDamage:\n      max: 2048.0\nmessages:\n  whitelist: You are not whitelisted on this server! Msg Kirin to be added\n  unknown-command: Unknown command. Type \"/help\" for help.\n  server-full: The server is full!\n  outdated-client: Outdated client! Please use {0}\n  outdated-server: Outdated server! I'm still on {0}\n  restart: Server is restarting\ncommands:\n  spam-exclusions:\n  - /skill\n  silent-commandblock-console: false\n  replace-commands:\n  - setblock\n  - summon\n  - testforblock\n  - tellraw\n  log: true\n  tab-complete: 0\n  send-namespaced: true\nadvancements:\n  disable-saving: false\n  disabled:\n  - minecraft:story/disabled\nstats:\n  disable-saving: false\n  forced-stats: {}\nworld-settings:\n  default:\n    view-distance: default\n    verbose: true\n    mob-spawn-range: 6\n    hopper-amount: 1\n    dragon-death-sound-radius: 0\n    seed-village: 10387312\n    seed-desert: 14357617\n    seed-igloo: 14357618\n    seed-jungle: 14357619\n    seed-swamp: 14357620\n    seed-monument: 10387313\n    seed-shipwreck: 165745295\n    seed-ocean: 14357621\n    seed-outpost: 165745296\n    seed-slime: 987234911\n    max-tnt-per-tick: 100\n    enable-zombie-pigmen-portal-spawns: true\n    item-despawn-rate: 6000\n    arrow-despawn-rate: 1200\n    wither-spawn-sound-radius: 0\n    hanging-tick-frequency: 100\n    zombie-aggressive-towards-villager: true\n    nerf-spawner-mobs: false\n    merge-radius:\n      exp: 3.0\n      item: 2.5\n    growth:\n      bamboo-modifier: 100\n      sweetberry-modifier: 100\n      kelp-modifier: 100\n      cactus-modifier: 100\n      cane-modifier: 100\n      melon-modifier: 100\n      mushroom-modifier: 100\n      pumpkin-modifier: 100\n      sapling-modifier: 100\n      beetroot-modifier: 100\n      carrot-modifier: 100\n      potato-modifier: 100\n      wheat-modifier: 100\n      netherwart-modifier: 100\n      vine-modifier: 100\n      cocoa-modifier: 100\n    entity-activation-range:\n      raiders: 48\n      animals: 32\n      monsters: 32\n      misc: 16\n      tick-inactive-villagers: true\n    entity-tracking-range:\n      players: 48\n      animals: 48\n      monsters: 48\n      misc: 32\n      other: 64\n    ticks-per:\n      hopper-transfer: 8\n      hopper-check: 1\n    hunger:\n      jump-walk-exhaustion: 0.05\n      jump-sprint-exhaustion: 0.2\n      combat-exhaustion: 0.1\n      regen-exhaustion: 6.0\n      swim-multiplier: 0.01\n      sprint-multiplier: 0.1\n      other-multiplier: 0.0\n    max-tick-time:\n      tile: 50\n      entity: 50\n    squid-spawn-range:\n      min: 45.0\n"}}
  creationTimestamp: "2019-08-27T02:20:21Z"
  name: spigot
  namespace: default
  resourceVersion: "1205176"
  selfLink: /api/v1/namespaces/default/configmaps/spigot
  uid: 3888debd-c871-11e9-9a07-42010aa20057
