apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft-server
    env: production
  name: minecraft-server-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31837
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    name: minecraft-server
  sessionAffinity: None
  type: LoadBalancer
