apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pd-ssd
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk-manual-restore
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-map-volume
spec:
  storageClassName: ""
  volumeName: minecraft-pd-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
