apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spigot-server
  labels:
    name: spigot-server
    app: "spigot-server"
    env: "production"
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      name: spigot-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: spigot-server
        app: "spigot-server"
        env: "production"
    spec:
      automountServiceAccountToken: true
      containers:
      - name: spigot-server
        image: gcr.io/perfect-chalice-250601/spigot-server:b9419f9277f66438d549ecf40a8d558ccd10226f
        ports:
        - containerPort: 25565
          name: mc
        resources:
          requests:
            cpu: 1200m
            memory: 5Gi
          limits:
            cpu: 1500m
            memory: 5.5Gi
        volumeMounts:
        - name: minecraft-map
          mountPath: "/home/minecraft/server"
          readOnly: false
        - name: ops
          mountPath: "/home/minecraft/config/ops.json"
          readOnly: true
        - name: server-properties
          mountPath: "/home/minecraft/config/server.properties"
          readOnly: true
        - name: whitelist
          mountPath: "/home/minecraft/config/whitelist.json"
          readOnly: true
        - name: spigot
          mountPath: "/home/minecraft/config/spigot.yml"
          readOnly: true
      volumes:
      - name: minecraft-map
        persistentVolumeClaim:
          claimName: minecraft-map-volume
      - name: ops
        configMap:
          name: ops
      - name: server-properties
        configMap:
          name: server-properties
      - name: spigot
        configMap:
          name: spigot
      - name: whitelist
        configMap:
          name: whitelist
