apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spigot-server
  labels:
    name: spigot-server
    app: "spigot-server"
    env: "production"
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      name: spigot-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: spigot-server
        app: "spigot-server"
        env: "production"
    spec:
      automountServiceAccountToken: true
      containers:
      - name: spigot-server
        image: gcr.io/perfect-chalice-250601/spigot-server:4800d1f62413101cfac585956b57f644dd81c2cb
        ports:
        - containerPort: 25565
          name: mc
        resources:
          requests:
            cpu: 1400m
            memory: 5Gi
          limits:
            cpu: 1500m
            memory: 5.5Gi
        volumeMounts:
        - name: minecraft-map
          mountPath: "/home/minecraft/server"
          readOnly: false
        - name: whitelist
          mountPath: "/home/minecraft/config"
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: minecraft-map
        persistentVolumeClaim:
          claimName: minecraft-map-volume
      - name: whitelist
        configMap:
          name: whitelist
