apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spigot-server
  labels:
    name: spigot-server
    app: "spigot-server"
    env: "production"
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      name: spigot-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: spigot-server
        app: "spigot-server"
        env: "production"
    spec:
      automountServiceAccountToken: true
      containers:
      - name: spigot-server
        image: gcr.io/perfect-chalice-250601/spigot-server:b5ffccd8b8f7c9b83a3c68510f9ea6695f3d0d43
        env:
        - name: HEAPSIZE
          value: "8G"
        ports:
        - containerPort: 25565
          name: mc
        resources:
          requests:
            cpu: 3300m
            memory: 8Gi
        volumeMounts:
        - name: minecraft-map
          mountPath: "/home/minecraft/server"
          readOnly: false
        - name: whitelist
          mountPath: "/home/minecraft/config"
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: minecraft-map
        persistentVolumeClaim:
          claimName: minecraft-map-volume
      - name: whitelist
        configMap:
          name: whitelist
