name: deploy

on: [deployment]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: dipshit/kubectl@master
      with:
        params: 'apply -f k8s/dynamic'
